### ISSUE TITLE
Enable all modules in build

### ISSUE THREAD

**Issue by bananenpampe** [conda-forge/plumed-feedstock#37]
### Comment:

Dear Developers, 

@luthaf and I were wondering if it was possible to have plumed builds with all of the modules enabled?
We are currently setting up a tutorial that requires a module enabled, and it would greatly facilitate our setup if there was a conda installable option.

Best regards, 
Matthias

**Comment by Luthaf** [comment]
I just found https://github.com/plumed/plumed2/issues/986 which mention a separate plan for the distribution of plumed modules. It seems that this plan will take a lot of time and work, so enabling most/all modules here would be nice in the mean time!

**Comment by bananenpampe** [comment]
For now I will try with the masterclass 2022 build.

**Comment by GiovanniBussi** [comment]
So far we decided not to provide the contributed modules by default because the code is not checked by plumed developers. I personally think it's a kind of safety barrier.

You can check if masterclass builds are ok.

**Comment by GiovanniBussi** [comment]
Also notice that we currently built gromacs + plumed for another tutorial (by @maxbonomi).

You can try to start from here: https://github.com/plumed/conda/tree/isdd-2024

If you just need gromacs + plumed with a specific module enabled, it should be sufficient to:
- clone this repository
- create a new branch based on isdd-2024
- replace everywhere isdd-2024 with the label name you want for your tutorial
- enable the module you want modifying [this line](https://github.com/plumed/conda/blob/4d978c6de4467c81a6e87ce96d2e75f45733225d/plumed/build.sh#L29)

If you open a pull request, I can merge it so that your conda packages would be installable from our organization.

In the same repositories, there are other branches with someway different settings (with some modules enabled, and with lammps installed as well), that we used for tutorials/masterclasses in the past

**Comment by bananenpampe** [comment]
Thank you Giovanni!
I followed your instructions and opened a pull request.

**Comment by bananenpampe** [comment]
closed, with a new branch ipi-demo created in the feedstock
